version: '3'
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build:
      context: .
      args: 
        NODE_DEV: production
    environment:
      - NODE_ENV=production
    command: npm start